### World Bank SE4ALL Exploration

#### Import Dependencies

In [10]:
import pandas as pd
import os

#### Set the path to your file

In [11]:
file = os.path.join("Source Databases","World Bank - Sustainable Energy for All - All Countries.csv")

#### Read the csv

In [16]:
df_SE4ALL = pd.read_csv(file)
df_SE4ALL.head(10)

,Country Name,Country Code,Time,Time Code,Access to Clean Fuels and Technologies for cooking (% of total population) [2.1_ACCESS.CFT.TOT],Access to electricity (% of rural population with access) [1.2_ACCESS.ELECTRICITY.RURAL],Access to electricity (% of total population) [1.1_ACCESS.ELECTRICITY.TOT],Access to electricity (% of urban population with access) [1.3_ACCESS.ELECTRICITY.URBAN],Energy intensity level of primary energy (MJ/2011 USD PPP) [6.1_PRIMARY.ENERGY.INTENSITY],Renewable electricity output (GWh) [4.1.2_REN.ELECTRICITY.OUTPUT],Renewable electricity share of total electricity output (%) [4.1_SHARE.RE.IN.ELECTRICITY],Renewable energy consumption (TJ) [3.1_RE.CONSUMPTION],Renewable energy share of TFEC (%) [2.1_SHARE.TOTAL.RE.IN.TFEC],Total electricity output (GWh) [4.1.1_TOTAL.ELECTRICITY.OUTPUT],Total final energy consumption (TFEC) (TJ) [1.1_TOTAL.FINAL.ENERGY.CONSUM]
0,United States,USA,1990.0,YR1990,..,100,100,100,8.66657670426795,369241,11.5286468488794,2053170,4.17546218583434,3202813,49172281.02234
1,United States,USA,1991.0,YR1991,..,100,100,100,8.74349537733587,350142,10.7574142290523,2219454,4.50791959377071,3254890,49234551.633684
2,United States,USA,1992.0,YR1992,..,100,100,100,8.61274699225872,324316,9.91611011689915,2357618,4.76308310810846,3270597,49497729.653016
3,United States,USA,1993.0,YR1993,..,100,100,100,8.52935320875437,355578,10.4843256121149,2159242,4.28152840674077,3391520,50431570.104744
4,United States,USA,1994.0,YR1994,..,100,100,100,8.35152168582419,336458,9.74723552434506,2102316,4.08864139839829,3451830,51418449.19008
5,United States,USA,1995.0,YR1995,..,100,100,100,8.2341349169744,384343,10.801084989942,2447809,4.72655433519206,3558374,51788445.163416
6,United States,USA,1996.0,YR1996,..,100,100,100,8.10927770625647,422867,11.5814500482575,2539409,4.76393045060593,3651244,53304913.376244
7,United States,USA,1997.0,YR1997,..,100,100,100,7.83913386346723,403130,10.9778281257659,2432528,4.51426029882715,3672220,53885417.299308
8,United States,USA,1998.0,YR1998,..,100,100,100,7.56902635840737,365559,9.60858498243135,2447760,4.5342968895809,3804504,53983231.79112
9,United States,USA,1999.0,YR1999,..,100,100,100,7.42580269733143,351308,9.06920058095258,3186229,5.70972659311957,3873638,55803530.134692

#### Filter Data to 2015

In [17]:
df_SE4ALL_2015 = df_SE4ALL[df_SE4ALL["Time"] == 2015]
df_SE4ALL_2015.head()

,Country Name,Country Code,Time,Time Code,Access to Clean Fuels and Technologies for cooking (% of total population) [2.1_ACCESS.CFT.TOT],Access to electricity (% of rural population with access) [1.2_ACCESS.ELECTRICITY.RURAL],Access to electricity (% of total population) [1.1_ACCESS.ELECTRICITY.TOT],Access to electricity (% of urban population with access) [1.3_ACCESS.ELECTRICITY.URBAN],Energy intensity level of primary energy (MJ/2011 USD PPP) [6.1_PRIMARY.ENERGY.INTENSITY],Renewable electricity output (GWh) [4.1.2_REN.ELECTRICITY.OUTPUT],Renewable electricity share of total electricity output (%) [4.1_SHARE.RE.IN.ELECTRICITY],Renewable energy consumption (TJ) [3.1_RE.CONSUMPTION],Renewable energy share of TFEC (%) [2.1_SHARE.TOTAL.RE.IN.TFEC],Total electricity output (GWh) [4.1.1_TOTAL.ELECTRICITY.OUTPUT],Total final energy consumption (TFEC) (TJ) [1.1_TOTAL.FINAL.ENERGY.CONSUM]
25,United States,USA,2015.0,YR2015,100,100,100,100,5.40839253955352,568439,13.2285932109672,5097931,8.71693586705814,4297048,58483061.912448
52,United Kingdom,GBR,2015.0,YR2015,100,100,100,100,3.01731446844954,83551,24.8400504227664,429157.5,8.71168557437913,336356,4926228.068448
79,Belgium,BEL,2015.0,YR2015,100,100,100,100,4.74127411057829,14466,20.8000230056939,128345.2,9.20164053078148,69548,1394807.801616
106,France,FRA,2015.0,YR2015,100,100,100,100,4.10185369917219,89357,15.8576666299907,760300.4,13.4992623166677,563494,5632162.574256
133,Germany,DEU,2015.0,YR2015,100,100,100,100,3.6030941551038,187366,29.2317701223308,1183042,14.2062526977772,640967,8327614.784616

#### What 10 developed countries had the highest % use of renewable energy of total final energy consumption (TFEC) in 2015?

In [46]:
list_of_developed_countries_eu = ["Austria", "Belgium", "Denmark", "Finland", "France", "Germany", "Greece", "Ireland", "Italy", "Luxembourg", "Netherlands", "Portugal", "Spain", "Sweden", "United Kingdom", 
                                  "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Estonia", "Hungary", "Latvia", "Lithuania", "Malta", "Poland", "Romania", "Slovak Republic", "Slovenia", 
                                  "Iceland", "Norway", "Switzerland"]
list_of_developed_countries_other = ["Australia", "Canada", "Japan", "New Zealand", "United States"]
list_of_developed_countries = list_of_developed_countries_eu + list_of_developed_countries_other

#list of countries with developed economies based on 2014 WESP Country Classification per UN https://www.un.org/en/development/desa/policy/wesp/wesp_current/2014wesp_country_classification.pdf

df_SE4ALL_2015_developed = df_SE4ALL_2015[df_SE4ALL_2015["Country Name"].isin(list_of_developed_countries)]
df_SE4ALL_2015_developed['Renewable energy share of TFEC (%) [2.1_SHARE.TOTAL.RE.IN.TFEC]'] = df_SE4ALL_2015_developed['Renewable energy share of TFEC (%) [2.1_SHARE.TOTAL.RE.IN.TFEC]'].astype(float)

df_SE4ALL_2015_developed.sort_values(by=['Renewable energy share of TFEC (%) [2.1_SHARE.TOTAL.RE.IN.TFEC]'], inplace=True, ascending=False)

C:\Users\cdubi\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\cdubi\anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [52]:
df_SE4ALL_2015_developed[['Country Name', 'Renewable energy share of TFEC (%) [2.1_SHARE.TOTAL.RE.IN.TFEC]']].head(10)

,Country Name,Renewable energy share of TFEC (%) [2.1_SHARE.TOTAL.RE.IN.TFEC]
3157,Iceland,77.029689
4831,Norway,57.772002
430,Sweden,53.247770
403,Finland,43.235263
565,Latvia,38.098017
376,Austria,34.394992
241,Denmark,33.170277
754,Croatia,33.127467
4669,New Zealand,30.789176
3832,Lithuania,28.961179